reinterpret UInt16 colors as FixedPointNumbers (#13)
* reinterpret UInt16 colors as FixedPointNumbers

N0f16 is the type that is used to represent color channels in LasIO.

This fixes `LazIO.load` for point type 2 and 3, which would fail with:

```
ArgumentError: FixedPointNumbers.Normed{UInt16,16} is a 16-bit type representing 65536 values from 0.0 to 1.0; cannot represent 7168
```

* Added testcase.

Co-authored-by: Maarten Pronk <evetion@users.noreply.github.com>